"""
Schema contract and binding staleness checks.

P1.2 — validates that FlatBuffers-generated Mia/ bindings are consistent
with the source schema in schemas/mia.fbs, and that Python consumers can
import all expected types without error.
"""

from __future__ import annotations

import importlib
import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent.parent

SCHEMA_DIR = REPO_ROOT / "schemas"
MIA_BINDINGS_DIR = REPO_ROOT / "Mia"

EXPECTED_BINDING_MODULES = [
    "Mia.GPIOCommand",
    "Mia.GPIODirection",
    "Mia.GPIOResponse",
    "Mia.SensorTelemetry",
    "Mia.SensorType",
    "Mia.SystemStatus",
    "Mia.CommandAck",
    "Mia.CommandStatus",
    "Mia.DeviceInfo",
    "Mia.DeviceType",
    "Mia.LEDState",
    "Mia.LEDMode",
    "Mia.AIState",
    "Mia.VehicleTelemetry",
]

AUTOGEN_HEADER = "automatically generated by the FlatBuffers compiler"


@pytest.mark.unit
class TestBindingModulesExist:
    """All expected FlatBuffers binding modules must be importable."""

    @pytest.mark.parametrize("module_name", EXPECTED_BINDING_MODULES)
    def test_binding_importable(self, module_name: str):
        mod = importlib.import_module(module_name)
        assert mod is not None

    def test_mia_package_importable(self):
        import Mia  # noqa: F401


@pytest.mark.unit
class TestBindingHeaders:
    """Generated bindings must carry the FlatBuffers auto-generation header."""

    def _binding_py_files(self):
        return sorted(MIA_BINDINGS_DIR.glob("*.py"))

    def test_binding_directory_exists(self):
        assert MIA_BINDINGS_DIR.is_dir(), f"Mia/ bindings directory missing at {MIA_BINDINGS_DIR}"

    def test_all_bindings_have_autogen_header(self):
        missing_header = []
        for py_file in self._binding_py_files():
            if py_file.name == "__init__.py":
                continue
            if py_file.name == "vehicle_codec.py":
                continue
            content = py_file.read_text(encoding="utf-8", errors="replace")
            if AUTOGEN_HEADER not in content:
                missing_header.append(py_file.name)
        assert not missing_header, (
            f"These Mia/ files lack the FlatBuffers auto-generated header "
            f"and may have been hand-edited: {missing_header}"
        )


@pytest.mark.unit
class TestSchemaSourceExists:
    """Source FlatBuffers schemas must be present."""

    def test_main_schema_exists(self):
        assert (SCHEMA_DIR / "mia.fbs").is_file()

    def test_vehicle_schema_exists(self):
        assert (SCHEMA_DIR / "vehicle_telemetry.fbs").is_file()

    def test_generator_exists(self):
        assert (SCHEMA_DIR / "generate.py").is_file()


@pytest.mark.unit
class TestSchemaTablesMatchBindings:
    """Tables declared in the FlatBuffers schema should have matching bindings."""

    def _extract_table_and_enum_names(self, fbs_path: Path) -> set[str]:
        content = fbs_path.read_text(encoding="utf-8")
        pattern = re.compile(r"(?:table|enum|struct)\s+(\w+)")
        return set(pattern.findall(content))

    def test_main_schema_types_have_bindings(self):
        schema_types = self._extract_table_and_enum_names(SCHEMA_DIR / "mia.fbs")
        binding_files = {p.stem for p in MIA_BINDINGS_DIR.glob("*.py")} - {"__init__", "vehicle_codec"}
        missing = schema_types - binding_files
        assert not missing, (
            f"Schema defines types {missing} but no matching Mia/*.py binding exists. "
            f"Run 'python schemas/generate.py' to regenerate."
        )


@pytest.mark.unit
class TestNormalizedPayloadContract:
    """The normalized telemetry payload must include all generic PID fields."""

    def test_generic_pid_fields_present(self):
        from apps.rpi_backend.shared.telemetry import normalized_payload as _np
        try:
            fields = _np.GENERIC_PID_FIELDS
        except AttributeError:
            pytest.skip("normalized_payload module not available via this import path")
        expected = {"speed_kmh", "engine_rpm", "coolant_temp_c", "fuel_level_percent", "battery_voltage", "vin"}
        assert expected.issubset(fields), f"Missing generic PID fields: {expected - fields}"

    def test_valid_capability_classes(self):
        from apps.rpi_backend.shared.telemetry import normalized_payload as _np
        try:
            classes = _np.VALID_CAPABILITY_CLASSES
        except AttributeError:
            pytest.skip("normalized_payload module not available via this import path")
        assert "unknown" in classes
        assert "generic_pid_only" in classes
        assert "uds_read_only" in classes

    def test_build_payload_includes_timestamp(self):
        from apps.rpi_backend.shared.telemetry import normalized_payload as _np
        try:
            payload = _np.build_telemetry_payload(speed_kmh=60)
        except (AttributeError, TypeError):
            pytest.skip("build_telemetry_payload not available")
        assert "timestamp" in payload
        assert "speed_kmh" in payload
